apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
        - name: celery-worker
          image: fastapi-celery-app:latest
          imagePullPolicy: IfNotPresent
          command:
            [
              "celery",
              "-A",
              "app.celery_tasks.celery_app",
              "worker",
              "--loglevel=info",
              "--concurrency=1",
            ]
          env:
            - name: CELERY_BROKER_URL
              value: "amqp://guest:guest@rabbitmq-service:5672/"
            - name: CELERY_RESULT_BACKEND
              value: "redis://redis-service:6379/0"
            - name: HOSTS
              value: "host.docker.internal:8001,host.docker.internal:8002,host.docker.internal:8003"
            - name: REDIS_HOST
              value: "redis-service"
